# Generated by Django 3.1.7 on 2021-02-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'managed': False},
        ),
    ]