# Generated by Django 3.1.7 on 2021-05-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_main', '0002_auto_20210223_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('board_idx', models.AutoField(db_column='board_idx', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=300)),
                ('contents', models.CharField(blank=True, db_column='contents', max_length=65535, null=True)),
                ('hit_cnt', models.IntegerField(blank=True, db_column='hit_cnt', null=True)),
                ('created_datetime', models.DateField(blank=True, db_column='created_datetime', max_length=20, null=True)),
                ('creator_id', models.CharField(blank=True, db_column='creator_id', max_length=50, null=True)),
                ('updated_datetime', models.DateField(blank=True, db_column='updated_datetime', max_length=20, null=True)),
                ('updater_id', models.CharField(blank=True, db_column='updater_id', max_length=50, null=True)),
                ('deleted_yn', models.CharField(blank=True, db_column='deleted_yn', max_length=1, null=True)),
            ],
            options={
                'db_table': 't_board',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='todolist',
            table='todo_list',
        ),
    ]