# Generated by Django 3.1.7 on 2021-05-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_main', '0003_auto_20210528_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]